package com.demo.test.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

// default package
// Generated 28 Aug, 2020 11:10:36 AM by Hibernate Tools 5.4.2.Final

/**
 * Register generated by hbm2java
 */
@Entity
@Table(name = "register")
public class Register implements java.io.Serializable {

	private Integer id;
	private String name;
	private String email;
	private String password;
	private byte[] image;

	public Register() {
	}

	public Register(String name, String email, String password, byte[] image) {
		this.name = name;
		this.email = email;
		this.password = password;
		this.image = image;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

}
