// default package
// Generated 28 Aug, 2020 11:09:40 AM by Hibernate Tools 5.4.2.Final



/**
 * Register generated by hbm2java
 */
public class Register  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String email;
     private String password;
     private byte[] image;

    public Register() {
    }

    public Register(String name, String email, String password, byte[] image) {
       this.name = name;
       this.email = email;
       this.password = password;
       this.image = image;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


